### ISSUE TITLE
Any options how to suppress output from Execute-SqlDatabase or run silently?

### ISSUE THREAD

**Issue by jacobrillema** [max-ieremenko/SqlDatabase#1]
I am developing some pester scripts and I want to suppress the output of the Execute-SqlDatabase function. Any ideas on how to do that? I am running the following Powershell

$PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  316

Script     1.7.6      SqlDatabase                         {Invoke-SqlDatabase, New-SqlDatabase, Update-SqlDatabase, Create-SqlDatabase...}

**Comment by CalumOchkas** [comment]
Have you tried the standard `Out-Null` cmdlet or `> $null`?

**Comment by jacobrillema** [comment]
I did try both and no luck. I think at one point I did try to redirect all output to a file and it didn’t work. Not sure how the code is tied to the PowerShell output stream. I can try to get some more examples for you.

Sent from my Windows 10 device

________________________________

**Comment by max-ieremenko** [comment]
In the current implementation you are not able to suppress or redirect the output.
Will be fixed.

**Comment by jacobrillema** [comment]
Thanks for the follow-up. I think a new silent option built it would be nice on top of the changes to use normal stderr/stdout redirection with Powershell. My current use case is running Pester test scripts and I get a lot of noise on the output.

**Comment by max-ieremenko** [comment]
Fixed in version 1.7.7

**Comment by jacobrillema** [comment]
@max-ieremenko This is working perfect now, thanks for the quick response!
