### ISSUE TITLE
Postgres: run scripts as a non-superuser to check if they can do something silly

### ISSUE THREAD

**Issue by max-ieremenko** [max-ieremenko/SqlDatabase#53]
It is related to the discussion in the PR #50.

Created by @parmcoder

## Use-case
Somehow, I want to be able to run some scripts as a non-superuser to check if they can do something silly.
Not sure if I did that correctly, I wrote something like `SqlDatabase -database='Host=localhost;Username=myuser;Password=qwerty; Database=MyDatabase' -fromSql='SQL' [command]`.

## Problem
I technically wanna quickly create a database from a new cluster and run some scripts using `myuser`, but it will instead log me into the `myuser` database.
That database exists because I used your script to create it at first. Then, when I try to create new databases using another user, it breaks.

**Comment by max-ieremenko** [comment]
#### Existing use case

- there is no MyDatabase
- run $ SqlDatabase create "-database=Host=server;Username=postgres;Password=qwerty;Database=MyDatabase" -from=[02.create.sql](https://github.com/max-ieremenko/SqlDatabase/blob/master/Sources/IntegrationTests/PgSql/New/02.create.sql)

**Comment by max-ieremenko** [comment]
Create command assumes, that MyDatabase may not exist yet and changes the database name in the connection string to `null`.

It works perfectly for `postgres` user, because `postgres` database always exists.
For any other `myuser` it leads to "database myuser does not exist".

**Comment by parmcoder** [comment]
[From this comment](https://github.com/max-ieremenko/SqlDatabase/pull/50#issuecomment-2156034373)

> To make work the existing and your use case:
> 
> ```cs
> // builder.Database = null;
> builder.Database = "postgres"
> _connectionStringMaster = builder.ToString();
> ```

That will always log me into the `Postgres` database. 

DBA can prevent non-superusers from connecting to `postgres` database. My application relies heavily on the database because it is a client application. Unlike web applications that send requests to the server, the client application has to set roles in the database directly to the users.

Suppose you insist on doing it like this. Mark the documentation: "This command will always run the SQL script on the `postgres ` database".

**Comment by max-ieremenko** [comment]
The `create` command is designed to fall back to `postgres` database if the target one does not exist yet.
That is why `builder.Database = "postgres"` makes sense.

In your case, the target database already exists and you want to prevent switching to `postgres`.
For this, the `execute` command should be used.

The following changes are in the branch [feature/53](https://github.com/max-ieremenko/SqlDatabase/blob/feature/53/Sources/)
- `create` command can switch to a master database
- `execute`, `export`, and `upgrade` commands always work in the context of the target database

**Comment by parmcoder** [comment]
Thank you for your explanation! I see why it has to be like that. I will wait until the next release is out. 😄

**Comment by max-ieremenko** [comment]
released in version [4.2.2](https://github.com/max-ieremenko/SqlDatabase/releases/tag/4.2.2)
